routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Auth::routes();

Route::get('/home', function () {
    return redirect('products');
})->name('home');

Route::middleware(['auth'])->group(function () {
    Route::resource('products', 'ProductController')->except('show');
    Route::post('deductProduct/{id}', 'ProductController@deductProduct')->name('deduct');

    Route::get('users', 'UserController@index')->name('users.index');



    Route::middleware('isAdmin')->group(function () {
        Route::post('addProduct/{id}', 'ProductController@addProduct')->name('add');
        Route::get('history', 'HistoryController@index')->name('history.index');
        Route::get('history/{id}', 'HistoryController@show')->name('history.show');
    });
});

app/History.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class History extends Model
{
    protected $fillable = [
        'quantity',
        'product_id',
        'user_id',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function product()
    {
        return $this->belongsTo(Product::class);
    }
}

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\History;

class Product extends Model
{
    protected $fillable = [
        'name',
        'quantity',
        'description'
    ];

    public function history($type_quantity)
    {
        History::create([
            'quantity' => $type_quantity,
            'product_id' => $this->id,
            'user_id' => auth()->user()->id
        ]);

        return true;
    }

    public function addProduct()
    {
        $this->quantity++;
        $this->history('+1');
        return $this->save();
    }

    public function deductProduct()
    {
        if ($this->quantity > 0) {
            $this->quantity--;
            $this->history('-1');
            return $this->save();
        }

        return false;
    }

    public function histories()
    {
        return $this->hasMany(History::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'document', 'phone_number', 'role'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HistoryController.php
<?php

namespace App\Http\Controllers;

use App\History;
use Illuminate\Http\Request;
use App\Product;

class HistoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $history = History::all()->sortByDesc('id');
        return view('history.index', compact('history'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\History  $history
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::find($id);
        return view('history.show', compact('product'));
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\History;
use App\Product;
use Illuminate\Http\Request;
use Validator;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        return view('products.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $v = Validator::make($request->all(), [
            'name' => 'required|unique:products',
            'quantity' => 'required|min:1',
        ]);

        if ($v->fails()) {
            return back()->withErrors($v->errors());
        }

        Product::create($request->all());

        return redirect('products')->with('msg', 'Creado correctamente');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Product $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('products.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Product $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $product->update($request->all());
        return redirect('products')->with('msg', 'Editado correctamente', 200);
    }

    public function addProduct($id)
    {
        $product = Product::find($id);
        $product->addProduct();
        return response()->json(['message' => 'Actualizado correctamente'], 200);
    }

    public function deductProduct($id)
    {
        $product = Product::find($id);
        $product->deductProduct();
        return response()->json(['message' => 'Actualizado correctamente']);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;

class UserController extends Controller
{
    public function index()
    {
        $users = User::all();
        return view('users.index', compact('users'));
    }
}

resources/views/history/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="card">
        <div class="card-header card-header-primary">
            <h4 class="card-title">Historial de productos</h4>
            <p class="card-category"> Información sobre productos</p>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table">
                    <thead class=" text-primary">
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Type</th>
                        <th>Name user</th>
                        <th>Quantity</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($history as $h)
                        <tr>
                            <td>{{$h->id}}</td>
                            <td>{{$h->product->name}}</td>
                            <td>{{$h->quantity}}</td>
                            <td>{{$h->user->name}}</td>
                            <td>{{$h->product->quantity}}</td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/history/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="card">
        <div class="card-header card-header-primary">
            <h4 class="card-title">Historial de {{$product->name}}</h4>
            <p class="card-category"> Información sobre productos</p>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table">
                    <thead class=" text-primary">
                    <tr>
                        <th>Quantity</th>
                        <th>Name</th>
                        <th>Date</th>
                    </tr>
                    </thead>
                    <tbody>

                    @foreach($product->histories as $h)
                        <tr>
                            <td>{{$h->quantity}}</td>
                            <td>{{$h->user->name}}</td>
                            <td>{{$h->created_at}}</td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/layouts/app.blade.php
<!--
            Oscar Amado
            facebook: www.facebook.com/ofaaoficial
            github: www.github.com/ofaaoficial
    -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ config('app.name', 'Inventorfa') }} - ofaaoficial</title>
    <script src="{{ asset('js/app.js') }}" defer></script>
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <meta name="author" content="Oscar Amado">
</head>

<body class="">
<div class="wrapper" id="app">
    @if(Auth()->user())
    <div class="sidebar" data-color="purple" data-background-color="white">
        <div class="logo">
            <a href="{{route('products.index')}}" class="simple-text logo-normal">
                Invetorfa
            </a>
        </div>
        <div class="sidebar-wrapper">
            <ul class="nav">
                <li class="nav-item active  ">
                    <a class="nav-link" href="{{route('products.index')}}">
                        <i class="material-icons">dashboard</i>
                        <p>Products</p>
                    </a>
                </li>
                @if(Auth()->user()->role == 'admin')
                    <li class="nav-item ">
                        <a class="nav-link" href="{{route('history.index')}}">
                            <i class="material-icons">history</i>
                            <p>History</p>
                        </a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="{{route('users.index')}}">
                            <i class="material-icons">person</i>
                            <p>Users</p>
                        </a>
                    </li>
                @endif
            </ul>
        </div>
    </div>

    <div class="main-panel">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
            <div class="container-fluid">
                <div class="navbar-wrapper">
                    <a class="navbar-brand" href="#pablo">Dashboard invertor</a>
                </div>
                <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="navbar-toggler-icon icon-bar"></span>
                    <span class="navbar-toggler-icon icon-bar"></span>
                    <span class="navbar-toggler-icon icon-bar"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end">

                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link" href="#pablo" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons">person</i>
                                {{Auth()->user()->name }}
                                <p class="d-lg-none d-md-block">
                                    Account
                                </p>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                         document.getElementById('logout-form').submit();">
                                    {{ __('Salir') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    @endif
        <!-- End Navbar -->
        <div class="content">
            @if(Session::get('msg') )
                <div class="alert alert-succes">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <i class="material-icons">close</i>
                    </button>
                    <span>
                    {{Session::get('msg')}}
                </div>

            @endif
            @yield('content')
        </div>
        <footer class="footer">
            <div class="container-fluid">
                <nav class="float-left">
                    <ul>
                        <li>
                            <a href="https://www.facebook.com/ofaaoficial">
                                Inventor
                            </a>
                        </li>
                    </ul>
                </nav>
                <div class="copyright float-right">
                    &copy;@{{   date}}
                    <a href="https://www.github.com/ofaaoficial" target="_blank">ofaaoficial</a>.
                </div>
            </div>
        </footer>
    </div>
</div>

</body>

</html>

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')
    <main class="py-4">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <a href="{{route('products.index')}}">
                                <button class="btn btn-danger btn-small float-right">Volver</button>
                            </a>
                            <h1>Crear producto</h1>
                        </div>
                        <div class="card-body">
                            <form action="{{route('products.store')}}" method="POST" id="register-product">
                                @include('products.form.form')
                                <div class="form-group">
                                    <button class="btn btn-success" @click.prevent="registerProduct">Register</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')
    <main class="py-4">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <a href="{{route('products.index')}}">
                                <button class="btn btn-danger btn-small float-right">Volver</button>
                            </a>
                            <h1>Editar producto</h1>
                        </div>
                        <div class="card-body">
                            <form action="{{route('products.update', $product->id)}}" method="POST">
                                @method('PUT')
                                @include('products.form.form')
                                <div class="form-group">
                                    <button class="btn btn-success">Actualizar</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
@endsection

resources/views/products/form/form.blade.php
@csrf
<div class="form-group">
    <label for="name">Name</label>
    <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" id="name" required @if(isset($product->name)) value="{{$product->name}}" @else value="{{ old('document') }}" @endif >
    @error('name')
    <span class="invalid-feedback" role="alert">
        <strong>{{ $message }}</strong>
    </span>
    @enderror
</div>

<div class="form-group">
    <label for="quantity">Quantity</label>
    <input type="number" class="form-control @error('quantity') is-invalid @enderror" name="quantity" id="quantity" required @if(isset($product->quantity)) value="{{$product->quantity}}" @else value="{{old('quantity')}}" @endif>
    @error('quantity')
    <span class="invalid-feedback" role="alert">
        <strong>{{ $message }}</strong>
    </span>
    @enderror
</div>

<div class="form-group">
    <label for="description">Description</label>
    <textarea name="description" id="description" cols="30" rows="10" class="form-control" required>@isset($product->description) {{$product->description}} @endisset</textarea>
</div>

<div class="form-group">
    <label for="type">Type</label>
    <select name="type" id="type" class="form-control" required>
        <option value="unidad">Unidad</option>
        <option value="paquete">Paquete</option>
    </select>
</div>

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="card">
        <div class="card-header card-header-primary">
            @if(Auth()->user()->role == 'admin')
                <a href="{{route('products.create')}}">
                    <button class="btn btn-success float-right">Crear</button>
                </a>
            @endif
            <h4 class="card-title ">Tabla de productos</h4>
            <p class="card-category"> Información sobre productos</p>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table">
                    <thead class=" text-primary">
                    <tr>
                        <th>ID</th>
                        <th>Type</th>
                        <th>Name</th>
                        <th>Quantity</th>
                        <th>Description</th>
                        @if(Auth()->user()->role == 'admin')
                            <th>Options</th>
                        @endif
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($products as $product)
                        <tr>
                            <td>{{$product->id}}</td>
                            <td>{{$product->type}}</td>
                            <td>{{$product->name}}</td>
                            <td>
                                <button class="btn btn-danger btn-small mr-2"
                                        @click.prevent="deductProduct({{$product->id}})">-
                                </button>

                                <span>{{$product->quantity}}</span>

                                @if(Auth()->user()->role == 'admin')
                                    <button class="btn btn-success btn-small ml-2"
                                            @click.prevent="addProduct({{$product->id}})">+
                                    </button>
                                @endif
                            </td>
                            <td>{{$product->description}}</td>
                            @if(Auth()->user()->role == 'admin')
                                <td>
                                    <a href="{{route('products.edit', $product->id)}}">
                                        <button class="btn btn-small btn-outline-success">Editar</button>
                                    </a>
                                    <a href="{{route('history.show', $product->id)}}">
                                        <button class="btn btn-small btn-outline-primary">Historial</button>
                                    </a>
                                </td>
                            @endif
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="card">
        <div class="card-header card-header-primary">
            @if(Auth()->user()->role == 'admin')
                <a href="{{route('register')}}">
                    <button class="btn btn-success float-right">Crear</button>
                </a>
            @endif
            <h4 class="card-title ">Tabla de usuarios</h4>
            <p class="card-category"> Información de los usuarios del sistema.</p>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table">
                    <thead class=" text-primary">
                    <tr>
                        <th>ID</th>
                        <th>Document</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Phone number</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($users as $user)
                        <tr>
                            <td>{{$user->id}}</td>
                            <td>{{$user->document}}</td>
                            <td>{{$user->name}}</td>
                            <td>{{$user->email}}</td>
                            <td>{{$user->phone_number}}</td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection